### ISSUE TITLE
BE - ***Slides that Need attributes.primary or attributes.secondary information***

### ISSUE THREAD

**Issue by nam20485** [hackoregon/civic-sandbox#10]
**Slide 011** - demolitions
https://service.civicpdx.org/neighborhood-development/sandbox/slides/demolitions/?format=json
- slide_meta.attributes.primary.field should be “description”

**Comment by nam20485** [comment]
hackoregon/neighborhoods-2018#94

**Comment by nam20485** [comment]
Merged and deployed.

**Comment by mendozaline** [comment]
Despite the changes made, this has not taken effect in the actual endpoint. 

It still reads `null` and not `description`:  https://service.civicpdx.org/neighborhood-development/sandbox/slides/demolitions/?format=json

**Comment by mendozaline** [comment]
This now works as intended.
