### ISSUE TITLE
BE - ***Change Visualization Type***

### ISSUE THREAD

**Issue by nam20485** [hackoregon/civic-sandbox#9]
**Foundation 043** - Eviction Rate
***Note - this data may not be retained (Aurelia)***
http://service.civicpdx.org/neighborhood-development/sandbox/foundations/evictionrate/?format=json
- Set slide_meta.attributes.visualization.type to "Text"

**Comment by nam20485** [comment]
Issue hackoregon/neighborhoods-2018#92 and PR hackoregon/neighborhoods-2018#93 created to support this item.

**Comment by nam20485** [comment]
hackoregon/neighborhoods-2018#92 closed.

**Comment by mendozaline** [comment]
Despite the changes made, this has not taken effect in the actual endpoint. 

It still reads `PercentDonut` and not `Text`: https://service.civicpdx.org/neighborhood-development/sandbox/foundations/evictionrate/?format=json

**Comment by mendozaline** [comment]
This now works as intended.
